[features]
seeds = false
[programs.devnet]
myepicproject = "CBc1wnz24czY93aUPPd8xaFEtEp7u6hH5uwRCmfuc2dD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/allenzhong/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
#test = "yarn run mocha -t 1000000 tests/"
